name: build-test

on: push

jobs:
  install:
    name: Run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        id: install
        run: ./install.sh
        shell: bash
      
      - name: Check
        if: steps.install.outputs.count_credential_challenges != 1
        run: exit 1